# Generated by Django 3.1.3 on 2020-11-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='cse_email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='cse_email_pass',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='ldap_email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='ldap_pass',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='moodle_id',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='moodle_pass',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
