# Generated by Django 3.1.3 on 2020-11-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapi', '0002_auto_20201117_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
